spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  datasource:
    driverClassName: org.postgresql.Driver
    password: ${POSTGRES_DB_PASSWORD:postgres}
    username: ${POSTGRES_DB_USERNAME:postgres}
    url: jdbc:postgresql://${POSTGRES_DB_HOST:localhost:5432}/${POSTGRES_DB_NAME:sensors-monitor}